"""Shared LLM instructions. The system prompt encodes the founding principle."""

SCRIBE_SYSTEM = (
    "You are a FAITHFUL MEDICAL SCRIBE. You transcribe, clean, and STRUCTURE only what "
    "was actually said in a doctor-patient consultation. Hard rules:\n"
    "- NEVER invent symptoms, findings, diagnoses, or history that was not spoken.\n"
    "- NEVER suggest, recommend, or decide treatment.\n"
    "- NEVER author a prescription. Medications that were discussed are captured "
    "verbatim and marked non-authoritative.\n"
    "- For every item you output, populate `provenance.span_ids` with the transcript "
    "segment id(s) the item came from. If you cannot cite a span, do not output it.\n"
    "- If something was not discussed, leave it empty.\n"
    "- Your output MUST conform exactly to the provided JSON schema."
)

CLEAN_INSTRUCTION = (
    "Correct ONLY unambiguous speech-to-text word errors while preserving the exact clinical "
    "meaning, the speaker labels, and the segment ids.\n"
    "HARD CONSTRAINTS (safety-critical — breaking these fabricates clinical data):\n"
    "- NEVER change any number, dose, quantity, strength, frequency, vital value, age, or "
    "date. Copy every numeric token EXACTLY as transcribed — e.g. '1 mg' stays '1 mg'; do "
    "NOT 'normalize' it to a typical dose such as '40 mg'.\n"
    "- NEVER substitute a drug or medical term for a different one you believe was intended. "
    "Keep the spoken token as-is even if it is not a recognized drug name (e.g. leave "
    "'Irtrizol' unchanged — do NOT rename it to 'Itraconazole').\n"
    "- Only fix obvious non-clinical transcription noise (clear misspellings of common words, "
    "spacing, punctuation). When in any doubt, leave the text unchanged.\n"
    "Log every change in `corrections`. Do not add, summarize, infer, or remove content."
)

RELATIONSHIP_INSTRUCTION = (
    "Determine WHO the consultation is clinically ABOUT before anything else. The patient "
    "is the person whose symptoms/history are described — NOT necessarily the person "
    "speaking. A parent, spouse, guardian, or translator often speaks ON BEHALF of the "
    "patient (e.g. 'my son has had fever' => the patient is the son, the speaker is the "
    "mother/caregiver; 'I am speaking for my father' => patient is the father).\n"
    "- Identify the DOCTOR by behavior (asks questions, examines, advises), not by who "
    "spoke first. The first speaker is NOT necessarily the clinician.\n"
    "- A TRANSLATOR/interpreter relays another person's words — they are NOT the patient; "
    "the patient is the person whose symptoms are being relayed.\n"
    "- Set `referenced_patient` to a short label for the PRIMARY patient (e.g. 'son', "
    "'father', 'wife', or 'patient' when the speaker describes their own symptoms).\n"
    "- If MORE THAN ONE person is described (e.g. a parent reports on two children, or "
    "'my son has fever and I also have a cough'), list every distinct patient in "
    "`referenced_subjects` with a short `label`, the speaker's `relationship`, and the "
    "`evidence_span_ids` that mention them. The first subject must be the primary patient.\n"
    "- NEVER attribute a caregiver's own identity to the patient. Attribute every symptom, "
    "history, and finding to the correct referenced patient.\n"
    "- This is grounded like everything else: base it only on what was actually said."
)

#: The original (pre-hardening) extract prompt. Kept ONLY so the batch-mode benchmark can
#: reproduce the baseline accuracy and show a clean before/after for the strengthened
#: prompt below — it is never served by default. See ``app/eval/bench.py --candidate``.
EXTRACT_INSTRUCTION_V1_BASELINE = (
    "Extract the clinical entities that were MENTIONED in the transcript into the schema. "
    "Attach provenance span ids to every item; if you cannot cite a span, do not output it.\n"
    "Set `referenced_patient` to WHO the complaints are about (the person discussed, not "
    "necessarily the speaker; 'patient' if the speaker describes their own symptoms).\n"
    "MEDICATIONS (safety-critical): capture each under `medications_discussed` exactly as "
    "spoken. Copy `dose`, `route`, `frequency`, and `duration` VERBATIM from the transcript — "
    "NEVER normalize, round, or substitute a 'typical' or 'standard' value, and NEVER rename "
    "the drug to a similar real medication. If a spoken dose looks unusual (e.g. 'Pantoprazole "
    "1 mg'), still record it verbatim. Put the exact source phrase in `verbatim_text`. If a "
    "field was not spoken, leave it null — never fill it from medical knowledge.\n"
    "For each `examination` finding, set `region` to a canonical lowercase value: one of "
    "throat, nose, ear, oral_cavity, neck, chest, abdomen, cardiovascular, respiratory, "
    "neuro, skin, general. Map pharynx / tonsils / oropharynx / posterior pharyngeal wall "
    "→ throat."
)

EXTRACT_INSTRUCTION = (
    "Extract EVERY clinical entity that was MENTIONED in the transcript into the schema. "
    "Be exhaustive: decision-critical history and results are easy to miss — losing them is "
    "the most harmful error. Attach provenance span ids to every item; if you cannot cite a "
    "span, do not output it.\n"
    "Set `referenced_patient` to WHO the complaints are about (the person discussed, not "
    "necessarily the speaker; 'patient' if the speaker describes their own symptoms).\n"
    "CAPTURE THESE SECTIONS WHENEVER THEY ARE DISCUSSED (do not leave them empty if the "
    "transcript mentions them):\n"
    "- `past_medical_history`: every pre-existing / chronic condition and prior procedure the "
    "patient already has (e.g. diabetes, hypertension, prior surgery) WITH its stated duration "
    "or onset (e.g. 'diabetes for 8 years'). Smoking, alcohol and other substance/social "
    "history also belong here when stated (e.g. 'smoked 1 pack/day, reduced last year'). These "
    "are the risk factors a clinician relies on — never drop them.\n"
    "- `family_history`: conditions or procedures in relatives (e.g. 'father had bypass surgery "
    "at 52'). Record the relative and the stated age/detail.\n"
    "- `investigations`: every test/result discussed — ECG, stress test/TMT, echo, labs — and "
    "CRUCIALLY their findings and VALUES, copied verbatim (e.g. 'ECG: mild ST-segment "
    "depression', 'TMT positive', 'ejection fraction 48%', 'LDL 168 mg/dL', 'HDL low', "
    "'triglycerides high', 'LVH on echo'). Each numeric value is high-value — do not summarize "
    "it away or omit the number.\n"
    "CERTAINTY — keep suspected and confirmed separate (do NOT upgrade a possibility to a "
    "diagnosis):\n"
    "- Put tentative / suspected / 'possible' / 'suggests' / 'rule-out' / differential findings "
    "in `assessment` (e.g. 'positive stress test suggests possible myocardial ischemia; "
    "concerning for coronary artery disease'). Include differentials that were named (e.g. "
    "'palpitations — query AF / SVT / PVC').\n"
    "- Put only CONFIRMED / established conditions in `diagnosis` (e.g. an echo-confirmed LVH, a "
    "stated dyslipidemia). If the doctor only raised a possibility, it is an assessment, not a "
    "diagnosis.\n"
    "NUMBERS (safety-critical): preserve every number, age, duration, dose, measurement, "
    "percentage, lab value, distance and date EXACTLY as transcribed — copy the numeric token, "
    "never round, normalize, infer, or drop it.\n"
    "MEDICATIONS (safety-critical): capture each under `medications_discussed` exactly as "
    "spoken. Copy `dose`, `route`, `frequency`, and `duration` VERBATIM from the transcript — "
    "NEVER normalize, round, or substitute a 'typical' or 'standard' value, and NEVER rename "
    "the drug to a similar real medication. If a spoken dose looks unusual (e.g. 'Pantoprazole "
    "1 mg'), still record it verbatim. Put the exact source phrase in `verbatim_text`. If a "
    "field was not spoken, leave it null — never fill it from medical knowledge.\n"
    "For each `examination` finding, set `region` to a canonical lowercase value: one of "
    "throat, nose, ear, oral_cavity, neck, chest, abdomen, cardiovascular, respiratory, "
    "neuro, skin, general. Map pharynx / tonsils / oropharynx / posterior pharyngeal wall "
    "→ throat."
)

RISK_INSTRUCTION = (
    "Identify risk indications ALREADY PRESENT in the conversation (red-flag symptoms, "
    "allergies / adverse drug reactions, stated abnormal vitals). For each marker, cite the "
    "transcript span ids in `evidence_span_ids` AND quote the exact triggering words in "
    "`evidence_text` (e.g. the patient's own sentence).\n"
    "- Respect NEGATION: a patient denying a symptom or allergy ('no allergies', 'no chest "
    "pain') is NOT a risk — either omit it or emit it at severity 'info' with a clearly "
    "'denied / absent' message.\n"
    "- Do NOT flag the doctor's screening QUESTION as a finding; flag only what was actually "
    "reported.\n"
    "- Do NOT emit medication_mentioned or dosage_mentioned markers — those are produced "
    "deterministically from the grounded extraction.\n"
    "Do NOT diagnose or recommend. This is an attention aid for the reviewing clinician only."
)
